basic get resource working

diff --git a/library/resources/get b/library/resources/get
--- a/library/resources/get
+++ b/library/resources/get
@@ -1,40 +1,51 @@
 get() {
 
-# these describe the options that we want the get resource to have.
-# on a successful run, the parse funtion will remove all values that are specified
-  required_inputs=(
+  # these describe the options that we want the get resource to have.
+  # on a successful run, the parse funtion will remove all values that are specified
+    required_inputs=(
 'ORIGIN="http remote origin of a file"'
 'MD5="MD5 sum of remote file"'
 )
 
-# parse command line inputs 
-parse_inputs $@
+  # parse command line inputs 
+  parse_inputs $@
 
-# make sure that all required params were set
-if ! test "${required_inputs[*]}" == ' ' ; then 
+  # make sure that all required params were set
+  if ! test "${required_inputs[*]}" == ' ' ; then 
     echo all required inputs were not found. returning 1
     return 1
-fi
+  fi
 
-
-
-exit 0 
 
   if [[ -z $SHEEP_DEVELOP ]] ; then 
-      CURL_ARGS=' --silent '
+    CURL_ARGS=' --silent '
   fi
-  
-  echo curling \"curl --location --output ${CACHE_DIR}/${MD5} $ORIGIN   \"
-  if test -f ${CACHE_DIR}/${MD5} ; then 
-      debug "found file in local cache"
-  elif $( curl -o ${CACHE_DIR}/${MD5} $ORIGIN ) ; then 
-      debug "downloaded remote file"
-    else 
-      echo could not get remote file
+
+  local file_path=$(get_md5_path $MD5)
+
+  if test -f $file_path ; then 
+    debug "found file in local cache, verifying md5..."
+    if ! $( verify_cached_file $MD5 ) ; then 
+      echo "md5 of file $MD5 was not correct"
       return 1
+    fi
+    return 0
   fi
-  
+
+  debug "trying to download file..."
+  mkdir -p $(dirname $file_path )
+  curl --output $file_path $ORIGIN
+
+  if test $? -ne 0 ; then 
+    echo "could not download file"
+    return 1
+  fi
+
   # verify md5 of file in cache
-  verify_cached_file $MD5
+  if ! $(verify_cached_file $MD5) ; then 
+    echo file is invalid!
+    return 1
+  fi
+
   
 }
